### ISSUE TITLE
Task model

### ISSUE THREAD

**Issue by nvs2394** [capheshift/daily-scrum-api#2]
Task{
      date : String,
      isCompleted: Bool,
      content: String,
      createAt: Date.Now,
      estimation: Number
}

Create a Task.
Get Task By Id.
Get All Task By userId
Update Task
DeleteTask

**Comment by tam-pham-alpha** [comment]
I've created it on wiki, check it here. https://github.com/capheshift/daily-scrum-api/wiki/Models
